pyms:
  services:
    requests:
      data: ""
    swagger:
        path: "project/swagger"
        file: "swagger.yaml"
        url: "/swagger/"
        project_dir: "project.views"
    tracer:
        client: "jaeger"
        host: "localhost"
        component_name: "data-service"
    metrics: true
  config:
    DEBUG: false
    TESTING: false
    APP_NAME: data-service
    APPLICATION_ROOT : "/"