---
swagger: "2.0"
info:
  description: "This is a sample server data-service server."
  version: "1.0.0"
  title: "Swagger data-service"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: "Countries"
    description: "Everything about COVID in a country"
schemes:
  - "http"
paths:
  /country:
    get:
      tags:
        - "Countries"
      summary: "Get stats by country id"
      produces:
        - "application/json"
      parameters:
        - name: iso_code
          in: query
          required: true
          type: string
          description: ISO code of the country
        - name: from_date
          in: query
          required: true
          type: string
          description: Start date
        - name: to_date
          in: query
          required: true
          type: string
          description: End date
      responses:
        "200":
          description: "Active cases and vaccination details"
          schema:
            $ref: '#/definitions/Country'
      x-swagger-router-controller: "project.views.country"
      operationId: get
definitions:
  Country:
    type: "object"
    properties:
      id:
        type: "string"
      cases:
        type: "array"
        items:
          $ref: "#/definitions/Case"
      vaccinations:
        type: "array"
        items:
          $ref: "#/definitions/Vaccination"
  Case:
    type: "integer"
  Vaccination:
    type: "integer"

